{
 "title": "Bareos",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jobname",
    "label": "Backup job",
    "query": "label_values(bareos_bytes_saved, jobname)"
   }
  ]
 },
 "panels": [
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unterminated backup jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bareos_last_job_status{status=\"C\", last_selector=\"last\"})",
     "legendFormat": "Created jobs"
    },
    {
     "expr": "sum(bareos_last_job_status{status=~\"R|L|l|a|i\", last_selector=\"last\"})",
     "legendFormat": "Running jobs"
    },
    {
     "expr": "sum(bareos_last_job_status{status=~\"q|F|S|m|M|s|j|c|d|p\", last_selector=\"last\"})",
     "legendFormat": "Waiting jobs"
    }
   ]
  },
  {
   "title": "Backup errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bareos_last_job_status{status=~\"E|f\",last_selector=\"last\"}) by(jobname)",
     "legendFormat": "Errors {{ jobname }}"
    },
    {
     "expr": "sum(bareos_last_job_status{status=~ \"W|e\",last_selector=\"last\"}) by (jobname)",
     "legendFormat": "Warnings {{ jobname }}"
    }
   ]
  },
  {
   "title": "Time since last scheduled backup",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - max(bareos_last_job_start_unix_timestamp{jobname=~\"$jobname\",jobtype=\"B\", last_selector=\"last_successful\"}) by (jobname)  + 60*60",
     "legendFormat": "{{ backupjob }}"
    }
   ]
  },
  { "title": "Stored data summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Stored data per client",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bareos_bytes_saved{jobtype=\"B\"}) by (client)",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Stored files per client",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bareos_files_saved{jobtype=\"B\"}) by (client)",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Stored data per job",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bareos_bytes_saved{jobtype=\"B\"}) by (jobname)",
     "legendFormat": "{{ jobname }}"
    }
   ]
  },
  {
   "title": "Stored files per job",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bareos_files_saved{jobtype=\"B\"}) by (jobname)",
     "legendFormat": "{{ jobname }}"
    }
   ]
  },
  {
   "title": "Stored data details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "All backed up data",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes", "label": "Size" }
     ],
     "targets": [
      {
       "expr": "bareos_bytes_saved{jobname=~\"$jobname\", jobtype=\"B\"} > 0",
       "legendFormat": "Bytes {{ jobname }}"
      },
      {
       "expr": "bareos_files_saved{jobname=~\"$jobname\", jobtype=\"B\"} > 0",
       "legendFormat": "Files {{ jobname }}"
      }
     ]
    },
    {
     "title": "Backed up data",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes", "label": "Size" }
     ],
     "targets": [
      {
       "expr": "bareos_last_job_bytes_saved{jobname=~\"$jobname\",jobtype=\"B\", last_selector=\"last_successful\"}",
       "legendFormat": "Bytes {{ jobname }}"
      },
      {
       "expr": "bareos_last_job_files_saved{jobname=~\"$jobname\",jobtype=\"B\", last_selector=\"last_successful\"}",
       "legendFormat": "Files {{ jobname }}"
      }
     ]
    },
    {
     "title": "Backed up data (last full backup)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes", "label": "Size" }
     ],
     "targets": [
      {
       "expr": "bareos_last_job_bytes_saved{jobname=~\"$jobname\", jobtype=\"B\", last_selector=\"last_successful_full\"}",
       "legendFormat": "Bytes {{ jobname }}"
      },
      {
       "expr": "bareos_last_job_files_saved{jobname=~\"$jobname\", jobtype=\"B\", last_selector=\"last_successful_full\"}",
       "legendFormat": "Files {{ jobname }}"
      }
     ]
    }
   ]
  },
  { "title": "Storage Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Pool status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(bareos_pool_bytes{expired=\"false\", prunable=\"false\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(bareos_pool_bytes{expired=\"true\",prunable=\"false\"})",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(bareos_pool_bytes{prunable=\"true\"})",
     "legendFormat": "Prunable"
    }
   ]
  },
  {
   "title": "Pool wasted space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (bareos_pool_bytes{expired=\"false\", prunable=\"false\"} / on(pool) sum(bareos_pool_bytes) by(pool))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Stored data per pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(bareos_pool_bytes{prunable=\"false\", expired=\"false\"}) by(pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Prunable/expired stored data per pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(bareos_pool_bytes{prunable=\"true\"}) by(pool) + sum(bareos_pool_bytes{prunable=\"false\", expired=\"true\"}) by (pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Volumes per pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(bareos_pool_volumes{prunable=\"false\", expired=\"false\"}) by(pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Prunable/expired volumes per pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(bareos_pool_volumes{prunable=\"true\"}) by(pool) + sum(bareos_pool_volumes{prunable=\"false\", expired=\"true\"}) by (pool)",
     "legendFormat": "{{ pool }}"
    }
   ]
  }
 ]
}