name: Conventional Commit & PR

on:
  pull_request:
  # For forked repositories:
  # pull_request_target:
    # You can add specific pull request types too.
    # If this is omitted, the workflow will only executed on opened, synchronize, and reopened
    # which is enough for generic use cases.
    # Below is the list of supported pull request sub-events
    # types: [opened, reopened, ready_for_review, unlocked, synchronize]

jobs:
  cpr:
    name: Check PR for conventional style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/Namchee/conventional-pr
      - uses: Namchee/conventional-pr@v0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          close: false
          issue: false
          signed: false
          label: invalid
  commitlint:
    name: Run commitlint on the PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/ahmadnassri/action-commit-lint
      - uses: ahmadnassri/action-commit-lint@v2.1.4

  label:
    name: Label PR derived from the conventional commit messages
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: label
        # https://github.com/action-runner/conventional-labeler
        uses: action-runner/conventional-labeler@2.0.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
