name: Build dev binaries

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  cleanup:
    permissions:
      contents: write # for mknejp/delete-release-assets to delete release assets
    runs-on: ubuntu-latest

    steps:

    - name: Delete old release assets
      uses: mknejp/delete-release-assets@36f2f2d2982eacea19cfc67bf2644afe636dd8b4
      with:
        token: ${{ github.token }}
        tag: latest
        fail-if-no-assets: false
        assets: |
          bareos_exporter-*


  releases-matrix:
    name: Release Go Binary
    needs: cleanup
    runs-on: ubuntu-latest
    permissions:
      contents: write # for wangyoucao577/go-release-action to upload release assets
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v2
    - name: Set BUILD_TIME env
      run: echo BUILD_TIME=$(date -u +%Y%m%d-%H%M) >> ${GITHUB_ENV}
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.37
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        release_tag: latest
        overwrite: true
        asset_name: "bareos_exporter-${{ env.BUILD_TIME }}-${{ matrix.goos }}-${{ matrix.goarch }}"
